python train.py --gpu 1 \
--graph subgraph.txt \
--seed 4621 \
--epochs 10000 \
--hidden_size 768 \
--GNN_cite GCN \
--GNN_sim GraphSAGE \
--sim_calc attn \
--layers 2 \
--dropout 0.5 \
--learning_rate 1e-4 \
--ndcg_top_n 50 \
--top_k 15 \
--weight_decay 1e-5